version: '3'

env:
  COMPOSE_FILE: ./docker/docker-compose.yml

tasks:
  build:prod:
    desc: Build Docker Compose services.
    cmds:
      - docker compose -f $COMPOSE_FILE build

  start:prod:
    desc: Start Docker Compose services.
    deps: [build:prod]
    cmds:
      - docker compose -f $COMPOSE_FILE up -d

  stop:prod:
    desc: Stop Docker Compose services.
    cmds:
      - docker compose -f $COMPOSE_FILE down
