name: frontend

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: on-failure
    networks:
      - caddy
    labels:
      caddy: opencomet.io
      caddy.reverse_proxy: '{{upstreams 3001}}'
      caddy.reverse_proxy.transport: http
      caddy.reverse_proxy.transport.keepalive: 20s

networks:
  caddy:
    external: true
